name: Gradle Lint

on:
  push:
    branches: [ "cm-13.0" ]
  pull_request:
    branches: [ "cm-13.0" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v3
      - run: ./gradlew lint
