name: Gradle Build

on:
  push:
    branches: [ "cm-13.0" ]
  pull_request:
    branches: [ "cm-13.0" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [17, 21]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - uses: gradle/gradle-build-action@v3
      - run: ./gradlew clean build
